<?php

return [
    "Vasca da bagno",
    "Asciugacapelli",
    "Shampoo",
    "Balsamo",
    "Sapone per il corpo",
    "Bidet",
    "Lavatrice",
    "Asciugatrice",
    "Essenziali",
    "Grucce",
    "Biancheria da letto",
    "Cuscini e coperte extra",
    "Cassaforte",
    "TV",
    "Aria condizionata",
    "Riscaldamento",
    "Estintore",
    "Kit pronto soccorso",
    "Wi-fi",
    "Frigorifero",
    "Piatti e posate",
    "Macchina del caffè",
    "Parcheggio gratuito",
    "Ascensore",
    "Colazione inclusa",
];
